import { describe, expect, it } from "vitest";
import { buildDashboardMetrics } from "../lib/domain/aggregateMetrics";
import type { CalculatedOrder } from "../lib/domain/types";

describe("buildDashboardMetrics", () => {
  it("builds KPI, monthly, platform, and product margin metrics", () => {
    const metrics = buildDashboardMetrics([
      buildOrder({
        platform: "smartstore",
        orderMonth: "2026-01",
        productCode: "P-001",
        productName: "프리미엄 무선 충전기",
        optionName: "화이트",
        quantity: 2,
        grossSales: 100000,
        discountAmount: 10000,
        salesFee: 3000,
        paymentFee: 1000,
        fixedFee: 0,
        totalCost: 50000,
        netProfit: 40000,
        marginRate: 40000 / 90000,
        profitStatus: "healthy",
      }),
      buildOrder({
        platform: "smartstore",
        orderMonth: "2026-01",
        productCode: "P-001",
        productName: "프리미엄 무선 충전기",
        optionName: "화이트",
        quantity: 1,
        grossSales: 50000,
        discountAmount: 0,
        salesFee: 1500,
        paymentFee: 500,
        fixedFee: 0,
        totalCost: 35000,
        netProfit: 15000,
        marginRate: 0.3,
        profitStatus: "healthy",
      }),
      buildOrder({
        platform: "coupang",
        orderMonth: "2026-02",
        productCode: "P-002",
        productName: "저마진 테스트 상품",
        optionName: "기본",
        quantity: 1,
        grossSales: 30000,
        discountAmount: 0,
        salesFee: 2550,
        paymentFee: 660,
        fixedFee: 150,
        totalCost: 28000,
        netProfit: 2000,
        marginRate: 2000 / 30000,
        profitStatus: "low_margin",
      }),
      buildOrder({
        platform: "coupang",
        orderMonth: "2026-02",
        productCode: "P-003",
        productName: "적자 테스트 상품",
        optionName: "기본",
        quantity: 1,
        grossSales: 20000,
        discountAmount: 5000,
        salesFee: 1700,
        paymentFee: 330,
        fixedFee: 150,
        totalCost: 20000,
        netProfit: -5000,
        marginRate: -5000 / 15000,
        profitStatus: "loss",
      }),
      buildOrder({
        productCode: null,
        productName: "원가 미등록 상품",
        optionName: "기본",
        totalCost: null,
        netProfit: null,
        marginRate: null,
        profitStatus: "missing_cost",
      }),
      buildOrder({
        orderStatus: "canceled",
        totalCost: null,
        netProfit: null,
        marginRate: null,
        profitStatus: "excluded",
      }),
    ]);

    expect(metrics.summary).toEqual({
      totalSales: 185000,
      netProfit: 52000,
      averageMarginRate: 52000 / 185000,
      lossProductCount: 1,
      excludedOrderCount: 1,
      missingCostOrderCount: 1,
    });
    expect(metrics.monthly).toEqual([
      {
        orderMonth: "2026-01",
        totalSales: 140000,
        netProfit: 55000,
      },
      {
        orderMonth: "2026-02",
        totalSales: 45000,
        netProfit: -3000,
      },
    ]);
    expect(metrics.platforms).toEqual([
      {
        platform: "smartstore",
        totalSales: 140000,
        netProfit: 55000,
      },
      {
        platform: "coupang",
        totalSales: 45000,
        netProfit: -3000,
      },
    ]);
    expect(metrics.products).toEqual([
      {
        productCode: "P-001",
        productName: "프리미엄 무선 충전기",
        optionName: "화이트",
        platform: "smartstore",
        quantity: 3,
        totalSales: 140000,
        totalCost: 85000,
        salesFee: 4500,
        paymentFee: 1500,
        fixedFee: 0,
        feeTotal: 6000,
        shippingCost: 6000,
        netProfit: 55000,
        marginRate: 55000 / 140000,
        profitStatus: "healthy",
      },
      {
        productCode: "P-002",
        productName: "저마진 테스트 상품",
        optionName: "기본",
        platform: "coupang",
        quantity: 1,
        totalSales: 30000,
        totalCost: 28000,
        salesFee: 2550,
        paymentFee: 660,
        fixedFee: 150,
        feeTotal: 3360,
        shippingCost: 3000,
        netProfit: 2000,
        marginRate: 2000 / 30000,
        profitStatus: "low_margin",
      },
      {
        productCode: "P-003",
        productName: "적자 테스트 상품",
        optionName: "기본",
        platform: "coupang",
        quantity: 1,
        totalSales: 15000,
        totalCost: 20000,
        salesFee: 1700,
        paymentFee: 330,
        fixedFee: 150,
        feeTotal: 2180,
        shippingCost: 3000,
        netProfit: -5000,
        marginRate: -5000 / 15000,
        profitStatus: "loss",
      },
    ]);
  });
});

function buildOrder(overrides: Partial<CalculatedOrder> = {}): CalculatedOrder {
  return {
    platform: "smartstore",
    orderDate: "2026-01-03",
    orderMonth: "2026-01",
    orderId: "ORDER-001",
    productCode: "P-001",
    productName: "프리미엄 무선 충전기",
    optionName: "화이트",
    quantity: 1,
    grossSales: 10000,
    discountAmount: 0,
    paidAmount: 13000,
    settlementAmount: null,
    shippingFeeCharged: 3000,
    orderStatus: "completed",
    unitCost: 3000,
    shippingCost: 3000,
    packagingCost: 500,
    otherCost: 300,
    salesFee: 350,
    paymentFee: 234,
    fixedFee: 0,
    totalCost: 7384,
    netProfit: 2616,
    marginRate: 0.2616,
    profitStatus: "healthy",
    ...overrides,
  };
}
